//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 02:53:07 PM CDT 
//


package com.example.lachamba;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apellido_paterno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apellido_materno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="salario_mensual" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="hora_entrada" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="hora_salida" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nombre",
    "apellidoPaterno",
    "apellidoMaterno",
    "correo",
    "cargo",
    "salarioMensual",
    "horaEntrada",
    "horaSalida"
})
@XmlRootElement(name = "NuevoEmpleadoRequest")
public class NuevoEmpleadoRequest {

    @XmlElement(required = true)
    protected String nombre;
    @XmlElement(name = "apellido_paterno", required = true)
    protected String apellidoPaterno;
    @XmlElement(name = "apellido_materno", required = true)
    protected String apellidoMaterno;
    @XmlElement(required = true)
    protected String correo;
    @XmlElement(required = true)
    protected String cargo;
    @XmlElement(name = "salario_mensual", required = true)
    protected BigDecimal salarioMensual;
    @XmlElement(name = "hora_entrada")
    protected int horaEntrada;
    @XmlElement(name = "hora_salida")
    protected int horaSalida;

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the apellidoPaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoPaterno() {
        return apellidoPaterno;
    }

    /**
     * Sets the value of the apellidoPaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoPaterno(String value) {
        this.apellidoPaterno = value;
    }

    /**
     * Gets the value of the apellidoMaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoMaterno() {
        return apellidoMaterno;
    }

    /**
     * Sets the value of the apellidoMaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoMaterno(String value) {
        this.apellidoMaterno = value;
    }

    /**
     * Gets the value of the correo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * Sets the value of the correo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorreo(String value) {
        this.correo = value;
    }

    /**
     * Gets the value of the cargo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargo() {
        return cargo;
    }

    /**
     * Sets the value of the cargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargo(String value) {
        this.cargo = value;
    }

    /**
     * Gets the value of the salarioMensual property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSalarioMensual() {
        return salarioMensual;
    }

    /**
     * Sets the value of the salarioMensual property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSalarioMensual(BigDecimal value) {
        this.salarioMensual = value;
    }

    /**
     * Gets the value of the horaEntrada property.
     * 
     */
    public int getHoraEntrada() {
        return horaEntrada;
    }

    /**
     * Sets the value of the horaEntrada property.
     * 
     */
    public void setHoraEntrada(int value) {
        this.horaEntrada = value;
    }

    /**
     * Gets the value of the horaSalida property.
     * 
     */
    public int getHoraSalida() {
        return horaSalida;
    }

    /**
     * Sets the value of the horaSalida property.
     * 
     */
    public void setHoraSalida(int value) {
        this.horaSalida = value;
    }

}
