//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 01:19:44 PM CDT 
//


package com.example.lachamba;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.lachamba package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.lachamba
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmpleadosRegistradosResponse }
     * 
     */
    public EmpleadosRegistradosResponse createEmpleadosRegistradosResponse() {
        return new EmpleadosRegistradosResponse();
    }

    /**
     * Create an instance of {@link EliminarEmpleadoResponse }
     * 
     */
    public EliminarEmpleadoResponse createEliminarEmpleadoResponse() {
        return new EliminarEmpleadoResponse();
    }

    /**
     * Create an instance of {@link ActualizarEmpleadoRequest }
     * 
     */
    public ActualizarEmpleadoRequest createActualizarEmpleadoRequest() {
        return new ActualizarEmpleadoRequest();
    }

    /**
     * Create an instance of {@link EmpleadosRegistradosResponse.Empleado }
     * 
     */
    public EmpleadosRegistradosResponse.Empleado createEmpleadosRegistradosResponseEmpleado() {
        return new EmpleadosRegistradosResponse.Empleado();
    }

    /**
     * Create an instance of {@link NuevoEmpleadoResponse }
     * 
     */
    public NuevoEmpleadoResponse createNuevoEmpleadoResponse() {
        return new NuevoEmpleadoResponse();
    }

    /**
     * Create an instance of {@link BuscarEmpleadoRequest }
     * 
     */
    public BuscarEmpleadoRequest createBuscarEmpleadoRequest() {
        return new BuscarEmpleadoRequest();
    }

    /**
     * Create an instance of {@link ActualizarEmpleadoResponse }
     * 
     */
    public ActualizarEmpleadoResponse createActualizarEmpleadoResponse() {
        return new ActualizarEmpleadoResponse();
    }

    /**
     * Create an instance of {@link BuscarEmpleadoResponse }
     * 
     */
    public BuscarEmpleadoResponse createBuscarEmpleadoResponse() {
        return new BuscarEmpleadoResponse();
    }

    /**
     * Create an instance of {@link NuevoEmpleadoRequest }
     * 
     */
    public NuevoEmpleadoRequest createNuevoEmpleadoRequest() {
        return new NuevoEmpleadoRequest();
    }

    /**
     * Create an instance of {@link EmpleadosRegistradosRequest }
     * 
     */
    public EmpleadosRegistradosRequest createEmpleadosRegistradosRequest() {
        return new EmpleadosRegistradosRequest();
    }

    /**
     * Create an instance of {@link EliminarEmpleadoRequest }
     * 
     */
    public EliminarEmpleadoRequest createEliminarEmpleadoRequest() {
        return new EliminarEmpleadoRequest();
    }

}
